# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle" # Specify Gradle as the package ecosystem
    directory: "/" # Location of the `build.gradle` or `build.gradle.kts` file
    schedule:
      interval: "weekly" # Check for updates on a weekly basis
    commit-message:
      prefix: "deps" # Optional: customize commit message prefix
    pull-request-branch-name:
      prefix: "dependabot-gradle" # Optional: customize branch name prefix
    group:
      name: "all-dependencies" # Group name for dependencies
      # Combine all dependency updates into a single PR
      patterns:
        - "*"
