spring:
  application:
    name: attachment-store
  data:
    mongodb:
      auto-index-creation: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: []
    groupManagerClient:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - pl.edu.agh.gem.internal.client.RetryableGroupManagerClientException
        - java.io.IOException
      ignoreExceptions: [ ]

attachment:
  max-size: 5MB
  allowed-type:
    - image/jpeg
    - image/jpg
    - image/png
    - image/bmp

default:
  group:
    - "group-default-0.jpeg"
    - "group-default-1.jpeg"
    - "group-default-2.jpeg"
    - "group-default-3.jpeg"
    - "group-default-4.jpeg"
    - "group-default-5.jpeg"
    - "group-default-6.jpeg"
    - "group-default-7.jpeg"
    - "group-default-8.jpeg"
    - "group-default-9.jpeg"
  user:
    - "user-default-0.jpeg"
  blank:
    - "blank-default-0.jpeg"

group-manager:
  url: "group/manager/some/url"
  read-timeout: 1000ms
  connect-timeout: 1000ms
