openapi: 3.0.1
info:
  title: Attachment Store API
  version: v1
  description: API for managing user and group attachments.

paths:
  /external/users/attachments/{attachmentId}:
    put:
      operationId: updateUserAttachment
      summary: Update a user attachment.
      description: Updates the specified attachment for the given user.
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/AttachmentId'
      requestBody:
        $ref: '#/components/requestBodies/Base64EncodedAttachment'
      responses:
        '200':
          $ref: '#/components/responses/AttachmentUpdated'
        '400':
          $ref: '#/components/responses/InvalidAttachmentData'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/UserOrAttachmentNotFound'

  /external/groups/{groupId}/attachments/{attachmentId}:
    get:
      tags:
        - External Group
      operationId: getGroupAttachment
      summary: Retrieve a group attachment.
      description: Fetches the specified attachment for a group.
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/GroupId'
        - $ref: '#/components/parameters/AttachmentId'
      responses:
        '200':
          $ref: '#/components/responses/AttachmentRetrieved'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/GroupOrAttachmentNotFound'
    put:
      tags:
        - External Group
      operationId: updateGroupAttachment
      summary: Update a group attachment.
      description: Updates the specified attachment for a given group.
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/GroupId'
        - $ref: '#/components/parameters/AttachmentId'
      requestBody:
        $ref: '#/components/requestBodies/Base64EncodedAttachment'
      responses:
        '200':
          $ref: '#/components/responses/AttachmentUpdated'
        '400':
          $ref: '#/components/responses/InvalidAttachmentData'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/GroupOrAttachmentNotFound'

  /internal/users/{userId}/generate:
    post:
      tags:
        - Internal User
      operationId: generateUserAttachment
      summary: Generate a user attachment.
      description: Creates a new attachment for the specified user.
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '201':
          $ref: '#/components/responses/AttachmentGenerated'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    UserId:
      name: userId
      in: query
      required: true
      schema:
        type: string
      description: The ID of the user.
    GroupId:
      name: groupId
      in: path
      required: true
      schema:
        type: string
      description: The ID of the group.
    AttachmentId:
      name: attachmentId
      in: path
      required: true
      schema:
        type: string
      description: The ID of the attachment.

  requestBodies:
    Base64EncodedAttachment:
      required: true
      content:
        application/json:
          schema:
            type: string
            format: byte
          examples:
            exampleAttachment:
              value: "BASE64_ENCODED_ATTACHMENT_DATA"

  responses:
    AttachmentUpdated:
      description: Attachment updated successfully.
      content:
        application/vnd.gem.internal.v1+json:
          schema:
            $ref: '#/components/schemas/AttachmentResponse'
    AttachmentRetrieved:
      description: Attachment retrieved successfully.
      content:
        application/vnd.gem.internal.v1+json:
          schema:
            type: string
            format: byte
          example: "BASE64_ENCODED_ATTACHMENT_DATA"
    AttachmentGenerated:
      description: Attachment generated successfully.
      content:
        application/vnd.gem.internal.v1+json:
          schema:
            $ref: '#/components/schemas/AttachmentResponse'
    UserAttachmentNotFound:
      description: User attachment not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    GroupAttachmentNotFound:
      description: Group attachment not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UnsupportedMediaType:
      description: Unsupported media type of attachment.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    AttachmentTooLarge:
      description: Attachment size exceeds the maximum allowed limit.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UserWithoutGroupAccess:
      description: User does not have access to the specified group.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UserWithoutAccess:
      description: User does not have access to the specified attachment.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    UserAttachmentResponse:
      type: object
      properties:
        id:
          type: string
          description: The ID of the attachment.
    GroupAttachmentResponse:
      type: object
      properties:
        id:
          type: string
          description: The ID of the attachment.
    AttachmentResponse:
      type: object
      properties:
        id:
          type: string
          description: The ID of the attachment.
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.
